#+TITLE: [[../index.html][Assinei o Spotify]]

** Assinei o Spotify.
Tenho que começar admitindo que essa assinatura foi praticamente uma ação compulsiva. Eu já tinha (ainda tenho na realidade) o Youtube Premium, que acompanha o Youtube Music, e ambos tem a mesma biblioteca de músicas.

Então, o que foi tão atraente sobre o Spotify? Ele realmente vale os $19,90 mensais? Como fica a comparação entre o Youtube Premium e o Spotify? Descubra isso e muito mais, aqui, no Animal Planet- Pera, lugar errado… enfim, vamo pra rinha de assinaturas!

** Comparação entre os serviços
Não posso falar sobre assinaturas sem antes mencionar o valor que cada uma carrega. Vou começar com o Youtube Premium, já que é uma assinatura que tenho a um certo tempo e também é uma assinatura de uma plataforma que uso desde os 11 anos de idade (obrigado Xbox 360 por ter existido).

** Youtube Premium
Por mais que, aqui no Brasil, pagar pelo Youtube gera frases como “Bicho, tu tá pagando pelo Youtube? É sério isso?” ele por incrível que pareça é um bom serviço para que usa casualmente (um ser humano descente) e um serviço quase que indispensável para alguém que usa o Youtube com grande frequência (um viciado como vosso escritor).

Algumas das funções que o Youtube mais faz propaganda sobre é a falta de anúncios e reprodução em segundo plano, ele inclusive tem uma aba dedicada somente para te mostrar quantas horas de anúncios você deixou de ver, quantas horas de mídia em segundo plano você reproduziu, quantos vídeos offline você assitiu e quantas horas de músicas você escutou. Me usando de exemplo, eu tenho o total de:

| Anúncios pulados  | Reprodução em segundo plano | Vídeos offline assistidos | Músicas escutadas |
|-------------------+-----------------------------+---------------------------+-------------------|
| Mais de 450 horas | Mais de 60 horas            | 486 vídeos                | Mais de 70 horas  |

Sim, eu “pulei” um total de 18 dias em anúncios. Eu não sei se fico contente ou revoltado com a audácia do Youtube contabilizar isso e achar que é uma coisa boa mostrar essa quantidade absurda de anúncios que eu não vi.

Deixa eu ser mais claro, o que eu quero dizer é que de todos os últimos 120 dias que eu tenho o Premium e assisto vídeos, praticamente 20 deles são o equivalente de anúncios a quem não é assinante, isso são aproximadamente 16,66% de todo o conteúdo que eu consumi (se eu fiz os cálculos corretamente).

Isso só quer dizer que o Youtube sem assinatura é praticamente inutilizável hoje em dia, não é atoa a má impressão que passa você pagar por um serviço que tem uma imagem tão ruim pelo usuário majoritário da plataforma.

Tendo dito tudo isso, o Youtube tem 2 tipos de assinaturas: O Youtube Music Premium, e o Youtube Premium. Os preços dos dois são respectivamente R$16,90 e R$20,90, porém, eu só vou considerar o plano mais caro como uma assinatura opcional, porque o Youtube Music é praticamente inutilizável sem a assinatura Premium, não porque ele limita o acesso à biblioteca ou algo do gênero, mas por conta dos anúncios altíssimos com frequência maior que o próprio Youtube e, para adicionar sal na ferida, a falta de reprodução em segundo plano, em um player de música. O Youtube Music só é um serviço competente se você pagar por ele.

Agora o Youtube Premium, ele sim é uma assinatura que faz um certo sentido, e além de tudo, traz consigo o Youtube Music Premium, que nessa perspectiva vira um brinde agradável que vem com sua assinatura.

** Spotify
Ao contrário da imagem negativa que Youtube Premium tem aqui em minha terra tupiniquim, o Spotify se qualquer coisa é quase um objeto de desejo, quase como um iPhone, não por ser caro mas por ser algo que é extremamente bem feito e bem pensado, tendo também a fama de ser o melhor no que faz.

Eu começei a usar o Spotify fazem apenas 5 dias, e já tenho coisas positivas para falar sobre ele. Uma delas é o Spotify Connect, que na minha perspectiva antes de usar o serviço, era só um recurso pra encher linguiça e que não tinha uma situação onde eu usaria essa função, até que eu, sem nem ter a intenção, acabei utilizando o recurso e vi o potencial dele. É algo quase como o ecossitema Apple de fazer as coisas, você só usa o seus dispositivos de forma natural, e sem você nem perceber, tudo fica interligado, e com isso você para de dinstinguir o seu celular da sua TV ou do seu computador. Tudo funciona como 1 aparelho que possui múltiplas formas de interagir.

Algo que me deixou surpreso e mudou a forma como eu escuto música, foram as playlists do Spotify. O Youtube Music tem algo similar com as estações de rádio e Mixes, mas as playlists criadas pelo Spotify com base no seu uso são simplesmente espetaculares, sem se falar nas playlists da comunidade que são realmente boas e também nas playlists com base em algum tema/artista/studio/série/filme que são publicadas pelo próprio Spotify.

No Youtube, as playlists que ele recomenda são quase sempre repetitivas, desconexas ou no pior dos casos, recheada de conteúdo que nem sequer é compatível com o Youtube Music, fazendo com que você tenha que abrir a playlist no Youtube, o que convenhamos, acaba completamente com a razão de você estar no Youtube Music.

Letras sincronizadas são outra função que eu nem sequer tinha conhecimento, mas que são algo que também, agregam na experiência do usuário. As letras tem uma cor de fundo que se aproxima das cores de destaque da capa do álbum, e no caso de uma música do oriente, tem uma transcrição em inglês da letra. Isso é algo que mostra o cuidado com a experiência de usuário que o Youtube parece não ter desde a criação do Youtube Music. Tudo o que você tem no Youtube Music é uma aba com a letra da música, que em alguns casos nem sequer tá completa, não tem sincronização com a música ou então está ausente ou simplesmente tá errada.

** Conclusão
Com tudo isso dito, só me resta agora chegar a minha conclusão e opinião sobre os serviços.

Em relação ao Youtube Premium, ele foi um serviço que eu adorei o período que experênciei, porém, não vou continuar com a assinatura. A única coisa que me prendeu ao serviço foi o Youtube Music, e como eu já verbalizei acima, ele em si não é um serviço bom quando deixado por conta própria, só servindo como um brinde agradável e não como algo indispensável.

Quanto ao Spotify, ele me mostrou entre outras coisas, o quanto que o Youtube Music tem a melhorar e o Youtube não parece ligar. Possui diversas funções que, se não úteis, são convenientes no mínimo, e além de tudo, não passa a impressão de um produto mal terminado e sem nenhum pensamento para o futuro.

Acho que já te fiz ler até demais. Até o próximo post!
