#+TITLE: [[../index.html][Bandcamp]]

** Mais outro serviço de música que eu estou usando ._.
Já faz mais de 1 mês desde a última vez que eu postei alguma coisa no blog, e justamente quando eu volto eu já estou com outro serviço de música para comentar.

** Qual a diferença dessa vez?
A diferença é bem simples: o Bandcamp não é um serviço de assinatura! Só isso mesmo… O modo em que o Bandcamp funciona é bem diferente do usual, nele você compra as músicas/álbuns/discografias ao invés de adicionar elas na sua biblioteca, e quando a compra é feita, você é direcionado para uma página de download dos arquivos. Sim, você baixa os arquivos dos álbuns.

A variedade de formatos de arquivos oferecido também é incrível. Você tem desde o famoso MP3 comum, ao MP3 320Kbps, Ogg Vorbis, AAC, FLAC, ALAC, WAV e AIFF.

** Também existem músicas gratuítas!
A melhor parte é que existem artistas/gravadoras que liberam as versões digitais de suas músicas gratuitamente para download ou streaming. Nas últimas semanas eu venho construindo uma biblioteca de músicas vindas do Bandcamp em conjunto com minhas músicas do Spotify, e bem… Eu já tenho 2300 músicas… Só do bandcamp… e outras 1400 no Spotify… É…

** /Fin/
É isso, me deculpe a demora, mas isso é tudo por hoje pessoal!
