#+TITLE: [[../index.html][Codeberg]]
-----

** Tchau, tchau, Github!
Pois é, passou-se apenas alguns dias desde o meu último post e eu
já mudei as coisas de novo. Estou com uma nova perspectiva em relação
a desenvolvimento e onde armazeno meus repositórios.

Agora eu uso o Codeberg no lugar do Github,
motivos? Só porque é open-source. Isso por si só já é motivo o suficiente
para eu migrar tudo do Github pra ele.

Eu não só migrei os repositórios que eu tinha no Github como também migrei
meu site inteiro, e até voltei a usar o Hugo para a criação do site.

Estou fazendo coisas novas no Codeberg também, como um repositório para
as minhas configurações do Vim, o que me lembra de algo…

** Amizade com o VSCode já era, Vim é o meu novo amigo.
Perdoe o meme reciclado, mas sim, eu estou usando o Vim no lugar do VSCode.

/“claro que você não está usando o Vim sem nenhum plugin… né?”/
/"…"/
/“você só pode tá de sacanagem.”/

É, eu não estou usando nenhum plugin. Isso não significa que eu esteja usando
a configuração padrão, Deus me livre, mas estou usando apenas as funções
nativas do Vim.

Tomei também a liberdade de alterar algumas teclas de atalho para algo
que é mais intuitivo para mim.

** Ok, cadê seu codeberg então?
Não precisa ser tão impaciente, ele está [[https://codeberg.org/tukain][aqui]].

** /Fin/
Enfim, é isso, espero ter te entretido.

Até o próximo post!
