#+TITLE: [[../index.html][Gemini]]

** Um protocolo muito interessante.
Nos últimos dias eu andei navegando no mundo do Gemini, um protocolo web com um foco em privacidade e simplicidade (e bota simplicidade nisso).
Andei procurando por "cápsulas" interessantes e me deparei com várias pérolas, como por exemplo o bbs.geminispace.org, que é um Bulletin Board, só que no Gemini.

** O foco desse protocolo
O foco do Gemini é ser um protocolo simples, privado e rápido, mas vamos dar um ênfase no *simples*.
O protocolo é um protocolo somente de texto, com uma request e uma resposta, nada a mais, nada a menos.
Ou seja, toda a parte de estilização da página fica por conta do seu cliente, que existe uma boa parcela por aí, sendo o meu preferido o Lagrange.

** Navegadores
Existem vários navegadores para o Gemini, alguns mais avançados como o Lagrange (um navegador de interface gráfica feito com SDL), outros mais simples como o astro (um navegador feito em shell-script), mas o que todos têm em comum é a navegação geral pelas páginas.
Todas as páginas do Gemini são arquivos de texto simples que seguem uma sintaxe também simples (o nome dela é Gemtext) e tudo o que o navegador precisa fazer é renderizar esse arquivo corretamente.

** A inspiração para o meu site
Como você já deve ter notado, eu reescrevi o meu site pela milionésima vez, dessa vez eu refiz ele usando o org-mode do Emacs, e um CSS de leve, e uma grande inspiração para o design do site foram as cápsulas Gemini.
Elas não tem muita coisa além de texto e links, então tomei isso como inspiração.

** /fin/
Bem, não sei mais o que dizer, eu estou escrevendo isso tarde e depois de um dia cansativo.

Enfim, te vejo no próximo post!
