#+TITLE: [[../index.html][Proton Pass]]

Ontem, por volta das 21:00 eu estava no ChromeOS Flex fazendo o usual, checando minhas senhas e excluindo contas redundantes, até que eu chego no site do Proton e percebo que o Proton Pass tinha acabado de lançar, e ele tinha bem mais funcionalidade do que eu esperava.

Começei a testar ele no navegador e no app mobile, e bem… adorei o serviço, tanto que em 1 hora de testes eu assinei o serviço pago, que me dá acesso à 20 Vaults (basicamente cofres aparte, algo como várias pastas para organização), configuração de TOTP (códigos de verificação aleatórios) e um número ilimitado de e-mail aliases (e-mails “falsos” que redirecionam os e-mails que recebem para sua caixa de entrada verdadeira).

A única coisa que me assustou foi a cobrança de aproximadamente R$120 no meu cartão de crédito, o porém é que isso foi culpa minha. Ao invés de ter selecionado a opção de pagamento mensal, eu deixei a opção de pagamento a cada 2 anos, o que explica a cobrança dos $24/R$120 (esse em si é um preço promocional de 80% de desconto devido ao lançamento do serviço, então até que não foi algo tão ruim assim).

Até o próximo post… E sempre tome cuidado com compras online.
