#+TITLE: [[../index.html][Spotify vs Youtube]]

** Isso vai ser difícil de decidir.
Nas últimas semanas eu vim usando o Spotify Premium junto da minha namorada, o que vem sendo uma experiência incrível, porém, o Youtube com o passar do tempo parece ser cada vez mais atraente, não acho que ele supere o Spotify em vários aspectos, mas ainda assim, ele continua sendo uma boa opção.

** Preços
Os preços de cada plano são extremamente diferentes

| Serviço                | Preço   | Pessoas no plano | Preço por pessoa |
|------------------------+---------+------------------+------------------|
| Spotify Duo            | R$27,90 |                2 | R$13,95          |
| Youtube Premium Family | R$41,90 |                5 | R$8,38           |

Como já está aparente, o Youtube é mais barato quando 5 pessoas fazem parte do plano e estão pagando, porém, é mais provável que no máximo 3 possam pagar, sendo assim ele custa ~R$14. Sendo assim ambos ficam empatados em questões monetárias. O que me resta agora é escolher qual deles eu irei deixar um cartão com renovação automática.

** A provável escolha final
Tenho quase total certeza de que eu irei ficar com o Spotify no fim das contas. Minha biblioteca já tem um valor emocional que me faz não querer trocar de plataforma, então é muito mais provável que eu fique com ele.

** /Fin/
Deve ser muito difícil ter que ler uma pessoa tão indecisa quanto eu, mas é isso, te vejo no próximo post!

