#+TITLE: [[../index.html][Atualizações]]
#+OPTIONS:  num:nil html-postamble:nil

#+HTML_HEAD:<style> 
#+HTML_HEAD: @import "../src/styles.css"
#+HTML_HEAD:</style>
-----

Quanto tempo, caro leitor! Espero que esteja tudo bem com você. Bom, perdoe a falta de artigos nos últimos tempos, os meses finais de 2023 foram muito agitados pra mim, fim da escola e etc.

Enfim, vamos às coisas que andei fazendo nos últimos meses. Canal no Youtube

Eu criei um canal no youtube no início desse ano, o nome dele é só um nome temporário, mas o que eu vou fazer nele já está decidido: Vídeos sobre ferramentas Linux.

Bom, o foco maior seria para ferramentas suckless, mas não faz mal comentar sobre outras coisas, como por exemplo o Neomutt (cliente de e-mail para terminal).

** Deletei uma porrada de contas
Outra coisa que fiz foi deletar uma porrada de contas, foi algo na casa de 6 contas de serviços diferentes, e eu ainda não terminei, falta muito para eu me sentir realmente satisfeito.

O que eu consideraria como contas essenciais seriam as minhas contas de E-mail, Github e Google, e vou reduzir ao máximo as demais. Fiz isso porque eu não gosto de redes sociais, nem de serviços que eu considero desnecessários.

Espero em breve ter o mínimo de contas possível, porque dessa forma será mais fácil de mante-las seguras com senhas novas a cada 7 ou 15 dias, autenticação de 2 fatores atualizada, códigos de recuperação re-gerados, enfim, vai ser algo que me beneficia a longo termo.

** VSCode virou meu Desktop
Apesar de não gostar da Microsoft, tenho que admitir que eu amo 2 produtos dela: O VSCode e o Github. A integração dos dois também é um puro deleite.

O meu workflow no VSCode é extremamente simples, porém, satisfatório. Dentro dele eu consigo:

- Editar o código de meus projetos
- Previsualizar eles em tempo real
- Formata-los automaticamente
- Compartilhar snippets com uma tecla de atalho
- Gerenciar o Git com extrema facilidade
- Entre outras coisas

Ultimamente eu não usava muito o meu computador, mas agora que eu comecei a estudar javascript, eu mal saio dele, principalmente por conta dessa experiência incrível com o VSCode. Vamos ver quanto tempo isso vai durar.

** Bem, é isso.
Acho que eu já disse tudo o que eu tinha a dizer, mas espero ter conseguido te entreter um pouco.

Até o próximo post!

