
#+TITLE: [[../index.html][Vivendo no Emacs]]
#+OPTIONS:  num:nil html-postamble:nil

#+HTML_HEAD:<style> 
#+HTML_HEAD: @import "../src/styles.css"
#+HTML_HEAD:</style>

-----
Sim. Eu enlouqueci.

** Como assim?

Bom, recentemente eu voltei a mexer no Emacs, eu já tinha feito isso a um tempo atrás, numa era sombria em que eu tinha uma conta no reddit.

*Senhor, tenha piedade de minha alma.*

Enfim, aquela configuração do Emacs foi a minha primeira experiência com ele, só que ela era… Digamos que não era lá muito boa.

Eu tava tentando fazer a minha própria versão do [[https://github.com/doomemacs/doomemacs][Doomemacs]], o que já vou adiantando:
É uma péssima idéia pra quem tá começando. Não é muito diferente de você ser novo em desenvolvimento de jogos e já querer fazer um The Last Of Us: Parte 69.
Vai dar merda, é só você que não percebeu ainda.

** E como está agora?

*MUITO* melhor. A primeira coisa que eu devo falar sobre a minha configuração é que, em comparação com a minha primeira vez, ela é muito mais estável, agradável de usar, rápida para iniciar e flexível. A configuração antiga parece uma gambiarra feita com fita isolante comparada à atual.

** O que tem nela?

Rapaz, eu configurei até que bastante coisa, várias teclas de atalho, pacotes, etc. Mas só pra listar, eu configurei:

- Um cliente de Email
- Um cliente de mpd
- Um cliente de irc
- Um leitor rss
- Um modo de apresentação de slides
- Um leitor de pdf
- Uma dashboard

Claro que tem mais coisa, como por exemplo as configurações da aparência, mas isso não é o mais interessante, o que realmente é interessante é…

** Sem Evil-mode

Isso sim é algo que poucos esperam, um Emacs, configurado, sem o Evil. Fiz isso porque eu quero aprender a usar o Emacs, não recriar o Vim, que foi +/- também o que fiz no passado. Estou aprendendo as teclas de atalho padrão do Emacs, e também tô fazendo as minhas próprias, e apesar de ser algo diferente do que eu estou acostumado, a experiência de usar o Emacs está sendo muito agradável.

A maior parte dos erros na minha configuração foram causados por erros de digitação, não porque um plugin X entrou em conflito com plugin Y ou porque uma tecla de atalho que eu configurei entra em conflito com uma tecla de atalho usada por um plugin que usa ela por algum motivo que só Deus sabe.

Não tô dizendo que isso é algo que aconteceu comigo enquanto eu usei o Vim, não, isso foi o que acontecia comigo na minha primeira configuração do Emacs. É, eu disse que aqueles eram tempos sombrios.

** /Fin/

Bem, é isso. Não vou ficar de papo sobre como o Org-mode é a 9ª maravilha do mundo nem nada do gênero, isso já foi dinfundido por cada ser que usa o Emacs no planeta, e eu não preciso ser mais um fazendo isso.

Até o próximo post!
