#+TITLE: [[../index.html][Workflow Web]]
#+OPTIONS:  num:nil html-postamble:nil

#+HTML_HEAD:<style> 
#+HTML_HEAD: @import "../src/styles.css"
#+HTML_HEAD:</style>
-----
Nos últimos meses passei a maior parte do meu tempo no navegador, não me refiro somente à consumo de mídia ou algo do gênero, me refiro a trabalhos de escola, documentos, roteiros, vídeos, entre outras diversas coisas que não muito tempo atrás eu utilizaria um programa dedicado para a tarefa.

Desde a concepção desse site eu já estava caminhando para esse tipo de Workflow mais centrado na Web, mas isso passou de uma caminhada para uma corrida e não muito tempo depois cá estou eu escrevendo esse artigo através do VSCode.dev.

Isso sim é algo que eu não esperaria vindo de mim, que até dezembro de 2022 usava o Alpine Linux com uma suíte de programas suckless como desktop principal e onde o meu Workflow era completamente offline (não é que eu não voltaria a ter esse workflow, mas atualmente ele seria imprático para mim).

Até o próximo post!


